import unittest

from knowledge_storm.answer_validation import (
    AnswerSchemaError,
    AnswerValidator,
    Claim,
    ClaimVerdict,
)
from knowledge_storm.paperstorm_qa import PaperStormKnowledgeBase


EVIDENCE = {
    "id": "paper-1::chunk-2",
    "chunk_id": "paper-1::chunk-2",
    "title": "Original Paper Title",
    "content": "Nonlinear junctions can generate passive intermodulation.",
    "url": "https://example.org/paper-1#page=3",
    "source": "local_pdf",
    "source_type": "local_pdf",
    "score": 1.0,
    "metadata": {
        "authors": ["Alice Zhang", "Bob Smith"],
        "page": 3,
        "section": "2.1 Mechanism",
    },
}


class StaticKnowledgeBase(PaperStormKnowledgeBase):
    def __init__(self, evidence=None):
        super().__init__(documents=[])
        self._evidence = list(evidence or [EVIDENCE])

    def search(self, query, top_k=3, **retrieval_options):
        self.retrieval_meta = {"stack": "test", "mode": "hybrid", "stages": []}
        return self._evidence[:top_k]


def draft(title="Invented Title", authors=None, text="PIM is generated by nonlinear junctions."):
    return {
        "answer": text,
        "answer_type": "abstractive",
        "claims": [
            {
                "claim_id": "claim-1",
                "text": text,
                "citations": [
                    {
                        "citation_id": "1",
                        "source_id": "invented-source",
                        "span": "invented span",
                        "title": title,
                        "authors": authors or ["Invented Author"],
                        "page": 99,
                        "section": "Invented",
                        "url": "https://invented.invalid",
                    }
                ],
            }
        ],
        "uncertainty": 0.1,
        "refusal": False,
        "abstain_reason": None,
    }


class PaperStormQAAnswerValidationTests(unittest.TestCase):
    def test_unvalidated_answer_keeps_body_and_appends_original_source(self):
        result = StaticKnowledgeBase().answer_question(
            "What causes PIM?", answer_generator=lambda _prompt: "legacy text"
        )
        self.assertTrue(result["answer"].startswith("legacy text"))
        self.assertIn("Original Paper Title", result["answer"])
        self.assertIn(EVIDENCE["url"], result["answer"])
        self.assertNotIn("answer_validation", result)
        self.assertNotIn("answer_validation", result["retrieval_metadata"])

    def test_validated_path_rehydrates_citation_and_reports_metrics(self):
        validator = AnswerValidator(lambda _claim, _registry: ClaimVerdict.ENTAILED)
        result = StaticKnowledgeBase().answer_question(
            "What causes PIM?",
            answer_generator=lambda _prompt: draft(),
            answer_validator=validator,
        )

        citation = result["citations"][0]
        self.assertEqual(citation["title"], "Original Paper Title")
        self.assertEqual(citation["authors"], ["Alice Zhang", "Bob Smith"])
        self.assertEqual(citation["span"], EVIDENCE["content"])
        self.assertEqual(citation["page"], 3)
        self.assertEqual(citation["section"], "2.1 Mechanism")
        self.assertEqual(citation["url"], EVIDENCE["url"])
        self.assertEqual(result["failure_type"], "")
        self.assertEqual(result["unsupported_claim_count"], 0)
        self.assertEqual(result["answer_validation"]["entailed_claim_count"], 1)
        self.assertEqual(
            result["retrieval_metadata"]["answer_validation"],
            result["answer_validation"],
        )

    def test_parse_retry_runs_at_most_once(self):
        calls = []

        def retry(raw, error):
            calls.append((raw, error))
            return draft()

        result = StaticKnowledgeBase().answer_question(
            "What causes PIM?",
            answer_generator=lambda _prompt: "invalid-json",
            answer_validator=AnswerValidator(
                lambda _claim, _registry: ClaimVerdict.ENTAILED
            ),
            answer_parse_retry=retry,
        )
        self.assertEqual(len(calls), 1)
        self.assertFalse(result["answer_validation"]["refusal"])

    def test_parse_error_is_not_swallowed(self):
        with self.assertRaises(AnswerSchemaError):
            StaticKnowledgeBase().answer_question(
                "What causes PIM?",
                answer_generator=lambda _prompt: "invalid-json",
                answer_validator=AnswerValidator(
                    lambda _claim, _registry: ClaimVerdict.ENTAILED
                ),
            )

    def test_failed_claim_is_locally_repaired_once_and_recorded(self):
        verifier_calls = []
        repair_calls = []

        def verifier(item, _registry):
            verifier_calls.append(item.text)
            return (
                ClaimVerdict.ENTAILED
                if item.text == "Evidence-bounded claim."
                else ClaimVerdict.UNSUPPORTED
            )

        def repair(item, assessment, _registry):
            repair_calls.append((item.claim_id, assessment.verdict))
            return Claim(
                claim_id=item.claim_id,
                text="Evidence-bounded claim.",
                citations=item.citations,
            )

        result = StaticKnowledgeBase().answer_question(
            "What causes PIM?",
            answer_generator=lambda _prompt: draft(text="Overstated claim."),
            answer_validator=AnswerValidator(verifier, repair=repair),
        )
        self.assertEqual(len(repair_calls), 1)
        self.assertEqual(len(verifier_calls), 2)
        self.assertTrue(result["answer"].startswith("Evidence-bounded claim."))
        self.assertIn("Original Paper Title", result["answer"])
        self.assertEqual(result["answer_validation"]["repair_attempt_count"], 1)

    def test_unrepaired_unsupported_claim_is_removed_and_refused(self):
        result = StaticKnowledgeBase().answer_question(
            "What causes PIM?",
            answer_generator=lambda _prompt: draft(text="Unsupported claim."),
            answer_validator=AnswerValidator(
                lambda _claim, _registry: ClaimVerdict.UNSUPPORTED
            ),
        )
        self.assertTrue(result["answer_validation"]["refusal"])
        self.assertEqual(result["failure_type"], "unsupported_claims")
        self.assertEqual(result["unsupported_claim_count"], 1)
        self.assertEqual(result["citations"], [])

    def test_missing_authors_remain_empty_in_canonical_citation(self):
        evidence = dict(EVIDENCE)
        evidence["metadata"] = dict(EVIDENCE["metadata"], authors=[])
        generated = draft(authors=["Invented Author"])
        result = StaticKnowledgeBase([evidence]).answer_question(
            "What causes PIM?",
            answer_generator=lambda _prompt: generated,
            answer_validator=AnswerValidator(
                lambda _claim, _registry: ClaimVerdict.ENTAILED
            ),
        )
        self.assertEqual(result["citations"][0]["authors"], [])


if __name__ == "__main__":
    unittest.main()
