import json
import unittest

from knowledge_storm.answer_validation import (
    AnswerDraft,
    AnswerSchemaError,
    AnswerValidator,
    Citation,
    Claim,
    ClaimVerdict,
    parse_answer_draft,
)


def citation(**overrides):
    data = {
        "citation_id": "c1",
        "source_id": "paper-1",
        "span": "Passive intermodulation is generated by nonlinear junctions.",
        "title": "Passive Intermodulation in RF Systems",
        "authors": ["A. Author", "B. Author"],
        "page": 3,
        "section": "2.1 Mechanism",
        "url": "https://example.org/paper-1",
    }
    data.update(overrides)
    return data


def claim(**overrides):
    data = {
        "claim_id": "q1",
        "text": "PIM can be caused by nonlinear junctions.",
        "citations": [citation()],
    }
    data.update(overrides)
    return data


def answer_draft(**overrides):
    data = {
        "answer": "Supported answer.",
        "answer_type": "abstractive",
        "claims": [claim()],
        "uncertainty": 0.1,
        "refusal": False,
        "abstain_reason": None,
    }
    data.update(overrides)
    return data


class SchemaTests(unittest.TestCase):
    def test_strict_schema_round_trip_preserves_provenance(self):
        draft = AnswerDraft.from_dict(answer_draft())
        restored = AnswerDraft.from_dict(draft.to_dict())
        self.assertEqual(restored, draft)
        self.assertEqual(restored.claims[0].citations[0].authors, ("A. Author", "B. Author"))
        self.assertEqual(restored.claims[0].citations[0].section, "2.1 Mechanism")

    def test_unknown_or_wrong_typed_fields_are_rejected(self):
        with self.assertRaises(AnswerSchemaError):
            Citation.from_dict(citation(extra="not allowed"))
        with self.assertRaises(AnswerSchemaError):
            Claim.from_dict(claim(citations="c1"))
        with self.assertRaises(AnswerSchemaError):
            AnswerDraft.from_dict({"answer": "x", "claims": [], "refusal": 1})

    def test_parser_retries_exactly_once(self):
        calls = []

        def retry(raw, error):
            calls.append((raw, error))
            return json.dumps(answer_draft(answer="fixed"))

        draft = parse_answer_draft("not-json", retry=retry)
        self.assertEqual(draft.answer, "fixed")
        self.assertEqual(len(calls), 1)

    def test_parser_does_not_retry_twice(self):
        calls = []

        def retry(raw, error):
            calls.append(raw)
            return "still-not-json"

        with self.assertRaises(AnswerSchemaError):
            parse_answer_draft("not-json", retry=retry)
        self.assertEqual(len(calls), 1)

    def test_strict_payload_requires_answer_contract_fields(self):
        for missing in ("answer_type", "uncertainty", "abstain_reason"):
            payload = answer_draft()
            payload.pop(missing)
            with self.subTest(missing=missing), self.assertRaises(AnswerSchemaError):
                parse_answer_draft(payload)

    def test_uncertainty_is_numeric_bounded_and_not_boolean(self):
        for value in (-0.01, 1.01, True, "0.2"):
            with self.subTest(value=value), self.assertRaises(AnswerSchemaError):
                AnswerDraft.from_dict(answer_draft(uncertainty=value))

    def test_direct_construction_cannot_bypass_semantic_validation(self):
        with self.assertRaises(AnswerSchemaError):
            AnswerDraft(
                answer="x",
                claims=(),
                uncertainty=2.0,
            )
        with self.assertRaises(AnswerSchemaError):
            AnswerDraft(
                answer="refused",
                claims=(),
                refusal=True,
                answer_type="refusal",
                abstain_reason=None,
            )

    def test_refusal_and_abstain_reason_are_consistent(self):
        with self.assertRaises(AnswerSchemaError):
            AnswerDraft.from_dict(
                answer_draft(refusal=True, answer_type="refusal", abstain_reason=None)
            )
        with self.assertRaises(AnswerSchemaError):
            AnswerDraft.from_dict(answer_draft(abstain_reason="not enough evidence"))

    def test_audit_serialization_derives_citation_ids(self):
        serialized = AnswerDraft.from_dict(answer_draft()).to_dict()
        self.assertEqual(serialized["citation_ids"], ["c1"])
        self.assertEqual(serialized["answer_type"], "abstractive")
        self.assertEqual(serialized["uncertainty"], 0.1)
        self.assertIsNone(serialized["abstain_reason"])


class ValidationTests(unittest.TestCase):
    def setUp(self):
        self.canonical = Citation.from_dict(citation())
        self.registry = {"c1": self.canonical}

    def test_supports_all_four_verdicts(self):
        verdicts = iter(
            [
                ClaimVerdict.ENTAILED,
                ClaimVerdict.PARTIAL,
                ClaimVerdict.CONTRADICTED,
                ClaimVerdict.UNSUPPORTED,
            ]
        )
        validator = AnswerValidator(lambda _claim, _evidence: next(verdicts))
        seen = [
            validator.assess(Claim.from_dict(claim(claim_id=str(i))), self.registry).verdict
            for i in range(4)
        ]
        self.assertEqual(
            seen,
            [
                ClaimVerdict.ENTAILED,
                ClaimVerdict.PARTIAL,
                ClaimVerdict.CONTRADICTED,
                ClaimVerdict.UNSUPPORTED,
            ],
        )

    def test_canonical_metadata_replaces_model_mutation(self):
        mutated = claim(
            citations=[citation(title="Invented", authors=["Fake"], page=99, url="bad")]
        )
        validator = AnswerValidator(lambda _claim, _evidence: ClaimVerdict.ENTAILED)
        result = validator.validate(
            AnswerDraft.from_dict(answer_draft(answer="x", claims=[mutated])),
            self.registry,
        )
        self.assertEqual(result.draft.claims[0].citations[0], self.canonical)

    def test_unknown_citation_cannot_be_accepted(self):
        validator = AnswerValidator(lambda _claim, _evidence: ClaimVerdict.ENTAILED)
        draft = AnswerDraft.from_dict(answer_draft(
            answer="x", claims=[claim(citations=[citation(citation_id="unknown")])]
        ))
        result = validator.validate(draft, self.registry)
        self.assertTrue(result.draft.refusal)
        self.assertEqual(result.draft.claims, ())

    def test_only_failed_claim_is_repaired_once(self):
        verify_calls = []
        repair_calls = []

        def verify(item, _evidence):
            verify_calls.append(item.claim_id)
            if item.claim_id == "ok" or "repaired" in item.text:
                return ClaimVerdict.ENTAILED
            return ClaimVerdict.UNSUPPORTED

        def repair(item, assessment, _evidence):
            repair_calls.append((item.claim_id, assessment.verdict))
            return Claim(
                claim_id=item.claim_id,
                text="repaired claim",
                citations=item.citations,
            )

        draft = AnswerDraft.from_dict(answer_draft(
            answer="two claims", claims=[claim(claim_id="ok"), claim(claim_id="bad")]
        ))
        result = AnswerValidator(verify, repair=repair).validate(draft, self.registry)
        self.assertEqual(repair_calls, [("bad", ClaimVerdict.UNSUPPORTED)])
        self.assertEqual(verify_calls.count("ok"), 1)
        self.assertEqual(verify_calls.count("bad"), 2)
        self.assertEqual(len(result.draft.claims), 2)

    def test_still_unsupported_claim_is_deleted(self):
        validator = AnswerValidator(
            lambda _claim, _evidence: ClaimVerdict.UNSUPPORTED,
            repair=lambda item, _assessment, _evidence: item,
        )
        result = validator.validate(
            AnswerDraft.from_dict(answer_draft(answer="unsupported")),
            self.registry,
        )
        self.assertTrue(result.draft.refusal)
        self.assertEqual(result.draft.claims, ())
        self.assertEqual(result.deleted_claim_ids, ("q1",))

    def test_partial_claim_is_downgraded_without_changing_citation(self):
        validator = AnswerValidator(lambda _claim, _evidence: ClaimVerdict.PARTIAL)
        result = validator.validate(
            AnswerDraft.from_dict(answer_draft(answer="partial")),
            self.registry,
        )
        kept = result.draft.claims[0]
        self.assertTrue(kept.text.startswith("现有证据仅部分支持："))
        self.assertEqual(kept.citations[0], self.canonical)
        self.assertEqual(result.downgraded_claim_ids, ("q1",))

    def test_contradicted_claim_is_deleted_but_supported_claim_remains(self):
        def verify(item, _evidence):
            return ClaimVerdict.ENTAILED if item.claim_id == "ok" else ClaimVerdict.CONTRADICTED

        draft = AnswerDraft.from_dict(answer_draft(
            answer="mixed", claims=[claim(claim_id="ok"), claim(claim_id="wrong")]
        ))
        result = AnswerValidator(verify).validate(draft, self.registry)
        self.assertFalse(result.draft.refusal)
        self.assertEqual([item.claim_id for item in result.draft.claims], ["ok"])
        self.assertEqual(result.deleted_claim_ids, ("wrong",))

    def test_validation_result_and_assessments_are_serializable(self):
        result = AnswerValidator(
            lambda _claim, _evidence: {
                "verdict": "entailed",
                "rationale": "span supports claim",
            }
        ).validate(AnswerDraft.from_dict(answer_draft()), self.registry)
        serialized = result.to_dict()
        self.assertEqual(serialized["assessments"][0]["verdict"], "entailed")
        self.assertEqual(serialized["assessments"][0]["rationale"], "span supports claim")
        self.assertEqual(serialized["draft"]["citation_ids"], ["c1"])


if __name__ == "__main__":
    unittest.main()
